language: rust

os:
- linux

rust:
- stable
- beta
- nightly

cache:
- apt

matrix:
  allow_failures:
  - rust: nightly
# https://medium.com/@tyrf/multi-target-rust-builds-with-auto-deployment-in-travis-ci-ab5214fb73ba
  include:
  - env:
    - NAME=YOURPACKETNAME
    - TARGET=arm-unknown-linux-gnueabihf
    - LINKER=arm-linux-gnueabihf-gcc
    - PACKAGE=$NAME-rpi2.tar.gz
    addons:
      apt:
        packages: &armhf
          - gcc-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross
  - env:
    - NAME=YOURPACKETNAME
    - TARGET=armv7-unknown-linux-gnueabihf
    - LINKER=arm-linux-gnueabihf-gcc
    - PACKAGE=$NAME-rpi3.tar.gz
    addons:
      apt:
        packages: *armhf
  - env:
    - NAME=YOURPACKETNAME
    - TARGET=i686-unknown-linux-gnu
    - PACKAGE=$NAME-i686.tar.gz
    addons:
      apt:
        packages:
        - gcc-multilib
  - env:
    - NAME=YOURPACKETNAME
    - TARGET=x86_64-unknown-linux-gnu
    - PACKAGE=$NAME-x86_64.tar.gz


install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add $TARGET || true
  - |
    if [ -n "$LINKER" ]; then
      mkdir -p ~/.cargo
      echo >> ~/.cargo/config
      echo "[target.$TARGET]" >> ~/.cargo/config
      echo "linker = \"$LINKER\"" >> ~/.cargo/config
    fi

before_script:
- PATH=$PATH:/home/travis/.cargo/bin
- apt install libssl-dev

script:
- |
  if [ $TARGET = "x86_64-unknown-linux-gnu" ]; then
    cargo test
  fi
- cargo build --target $TARGET --verbose --release

deploy:
  provider: releases
  api_key:
    secure: cbVPXdowaY7r6K2qLuSenc4GbGB6NpUOxfd3u3kAlqvaOK/cOLb+yFPQiskDK3AOidBGZf+Ywb5q60Rowu0nCWxM68ficS/mOOdR9/FvOroQR9mZDUHGyhGAUQ5V95eqqZsgJ6YDy023RIZzOe1nRSuaaDtmFIvMw2ba0gZnWLArE8Qp4XnM/zRWB+2SGg5i4aXsBxnKwFNFZ2f9spjq95XHtOwvDnesRmtEA0Uqh1A8amrWO226Obgd1K4AawhsEdQs5TGuSo5NdP6dmnvmkXmAHQuYOH+srZlWv/9eYkQNhNGeIaWyGZrU4Obf9tazrEPuVixBh5CpVZ73NaD4mpGRJqlogHkmdln4/3mMofIss0ZT+nHaygd2/OYg3S90S1wXURnUHoWR2gqqhLn8C3cye6ubE72zBZMIuU1qTcoLuVM72HoFF9YIWSB9Fq4j+eq7entSsLss2rI5qhnLOJdGp3bqyqkUHIrhSBk03U56RX3Twn9BziF30h6IQ/Khsm8UsuPWwkKBFKZUlPuWFKba51r2eU+77tcFtDNk5v+sFyMj47chhrfn57XRzRuJdQtNvij0GFhcMH/8GufWyS5H2BTmYldrj9V5+hP5krN7UT7ZPOxMpdTfkrVtTy2qtDx6Hzg2sl4EieZjsXx7jqrDmxr1YkPbghJ8fNCYOZs=
  file: target/release/beamium
  skip_cleanup: true
  on:
    repo: miton18/beamium
